version: "3.9"

services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: project_base_api
    container_name: project_base_api
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles:z 
    expose:
      - "8000"
    env_file:
      - .envs/.env.local
    depends_on:
      - postgres
      - mailpit
    command: /start
    networks:
      - project_base
      
  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    volumes:
      - project_base_postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.env.local
    networks:
      - project_base

  mailpit:
    image: docker.io/axllent/mailpit:v1.15
    container_name: project_base_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - project_base_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - project_base

networks:
  project_base:
    external: true

volumes:
  project_base_postgres_data: {}
  project_base_mailpit_data: {}
