# Generated by Django 4.2.11 on 2025-01-16 17:46

import autoslug.fields
import cloudinary.models
import core_apps.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6, verbose_name='Gender')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='BIO')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+201017595972', max_length=13, region=None, verbose_name='Phone Number')),
                ('country', django_countries.fields.CountryField(default='EGY', max_length=2, verbose_name='Country Field')),
                ('city_of_origin', models.CharField(default='Cairo', max_length=150, verbose_name='City')),
                ('report_count', models.IntegerField(default=0, verbose_name='Report Count')),
                ('reputation', models.IntegerField(default=100, verbose_name='Reputation')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=core_apps.profiles.models.get_user_username, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
